export function buildUniverseContextPrompt(universeLabel: string): string {
  return [
    "Tu es un architecte de contexte pour une pipeline multi-agent de compte-rendu JDR.",
    "",
    "Objectif:",
    "A partir de materiel source (livre de regles, guide de campagne, wiki, notes MJ), genere un bloc \"Contexte de l'univers\" optimise pour cette architecture:",
    "- Analyst: detecte scenes, speakers, entites, lieux, objets.",
    "- Summarizer: redige des resumes narratifs immersifs mais fideles.",
    "- Validator: detecte incoherences de continuite et de nomenclature.",
    "",
    "Univers cible:",
    `- ${universeLabel}`,
    "",
    "Materiaux source a analyser:",
    "{{COLLER_LES_EXTRAITS_OU_RESUMES_ICI}}",
    "",
    "Instructions critiques:",
    "1) N'invente rien. Si une information manque, indique \"inconnu\".",
    "2) Priorise la valeur operationnelle pour l'IA, pas le lore encyclopedique.",
    "3) Canonise les noms: forme principale + alias orthographiques usuels.",
    "4) Distingue les faits stables (canon), les variantes, et les zones incertaines.",
    "5) Fournis des reperes pour reconnaitre PNJs, lieux, factions, concepts et objets.",
    "6) Ajoute les conventions lexicales utiles (vocables, titres, jargon, toponymes).",
    "7) Donne des contraintes de style pour un resume immersif mais non-hallucinatoire.",
    "8) Reste compact, dense et exploitable directement dans un system prompt.",
    "",
    "Format de sortie STRICT (Markdown):",
    "# Contexte d'univers pour CR Session",
    "## 1. Vision d'ensemble (120-180 mots)",
    "- Ton global, themes, enjeux, type de conflits.",
    "",
    "## 2. Canon de nomenclature",
    "- Personnages/factions/lieux/objets sous forme:",
    "  - Nom canonique | Alias possibles | Description courte | Importance",
    "",
    "## 3. Entites importantes pour l'analyse",
    "- PJs typiques, PNJs notables, factions, institutions, creatures.",
    "- Signaux utiles pour les reconnaitre dans un transcript oral imparfait.",
    "",
    "## 4. Lieux et geographie narrative",
    "- Lieux majeurs, fonctions narratives, relations entre lieux.",
    "",
    "## 5. Mecanismes de jeu impactant le recit",
    "- Regles qui influencent clairement les decisions et scenes (jets, ressources, risques).",
    "",
    "## 6. Chronologie et continuite",
    "- Epoque, points d'ancrage, evenements deja etablis, points de vigilance.",
    "",
    "## 7. Lexique et formulations recommandees",
    "- Termes a privilegier / eviter pour garder coherence et tonalite.",
    "",
    "## 8. Garde-fous anti-hallucination",
    "- Ce qu'il ne faut pas extrapoler.",
    "- Comment traiter les ambiguitees.",
    "",
    "## 9. Resume ultra-court (10 lignes max)",
    "- Version compacte reutilisable dans des prompts courts.",
    "",
    "Contraintes finales:",
    "- Francais.",
    "- Pas de disclaimer, pas de meta-commentaire.",
    "- 700 a 1400 mots selon richesse du materiel.",
    "- Sortie directement copiable dans un champ \"Contexte de l'univers\".",
  ].join("\n");
}
